// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0FoJthG_EpWk2BerrrAeWJDB1tecnOS4',
    appId: '1:88092310883:web:4be228b5092412a734a756',
    messagingSenderId: '88092310883',
    projectId: 'belajarmdp-a82e8',
    authDomain: 'belajarmdp-a82e8.firebaseapp.com',
    databaseURL: 'https://belajarmdp-a82e8-default-rtdb.firebaseio.com',
    storageBucket: 'belajarmdp-a82e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmDPKTB4bTe42PVlaoX2byT7t7ip6kxgc',
    appId: '1:88092310883:android:f435a98fa1dfbf5834a756',
    messagingSenderId: '88092310883',
    projectId: 'belajarmdp-a82e8',
    databaseURL: 'https://belajarmdp-a82e8-default-rtdb.firebaseio.com',
    storageBucket: 'belajarmdp-a82e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbRy26wWIXniZ9ydsOCdQ8HabkCfSKSkk',
    appId: '1:88092310883:ios:df88ec600b0902eb34a756',
    messagingSenderId: '88092310883',
    projectId: 'belajarmdp-a82e8',
    databaseURL: 'https://belajarmdp-a82e8-default-rtdb.firebaseio.com',
    storageBucket: 'belajarmdp-a82e8.firebasestorage.app',
    iosBundleId: 'com.example.belajar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbRy26wWIXniZ9ydsOCdQ8HabkCfSKSkk',
    appId: '1:88092310883:ios:df88ec600b0902eb34a756',
    messagingSenderId: '88092310883',
    projectId: 'belajarmdp-a82e8',
    databaseURL: 'https://belajarmdp-a82e8-default-rtdb.firebaseio.com',
    storageBucket: 'belajarmdp-a82e8.firebasestorage.app',
    iosBundleId: 'com.example.belajar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0FoJthG_EpWk2BerrrAeWJDB1tecnOS4',
    appId: '1:88092310883:web:1b14666382a15f1734a756',
    messagingSenderId: '88092310883',
    projectId: 'belajarmdp-a82e8',
    authDomain: 'belajarmdp-a82e8.firebaseapp.com',
    databaseURL: 'https://belajarmdp-a82e8-default-rtdb.firebaseio.com',
    storageBucket: 'belajarmdp-a82e8.firebasestorage.app',
  );
}
