name: daftar_belanja
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_database: ^10.5.7

flutter:
  uses-material-design: true
