// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVjSlcsBtgvDCZoVoZvOyamxRVL_SN53c',
    appId: '1:1033382730877:web:757f1b050a0f76b13ae514',
    messagingSenderId: '1033382730877',
    projectId: 'notes-2ea4e',
    authDomain: 'notes-2ea4e.firebaseapp.com',
    storageBucket: 'notes-2ea4e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcnsIJA8wjat1D5Eeuz1g5JMLSNaiXSl4',
    appId: '1:1033382730877:android:82683ba3c44c73b13ae514',
    messagingSenderId: '1033382730877',
    projectId: 'notes-2ea4e',
    storageBucket: 'notes-2ea4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSfJ1DZGUYm564WcYgghY28xZrZ70tCZo',
    appId: '1:1033382730877:ios:b851f73918b12ada3ae514',
    messagingSenderId: '1033382730877',
    projectId: 'notes-2ea4e',
    storageBucket: 'notes-2ea4e.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSfJ1DZGUYm564WcYgghY28xZrZ70tCZo',
    appId: '1:1033382730877:ios:b851f73918b12ada3ae514',
    messagingSenderId: '1033382730877',
    projectId: 'notes-2ea4e',
    storageBucket: 'notes-2ea4e.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVjSlcsBtgvDCZoVoZvOyamxRVL_SN53c',
    appId: '1:1033382730877:web:107cbe9275dbd6323ae514',
    messagingSenderId: '1033382730877',
    projectId: 'notes-2ea4e',
    authDomain: 'notes-2ea4e.firebaseapp.com',
    storageBucket: 'notes-2ea4e.firebasestorage.app',
  );
}
