// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoU6Zj8bexW-wS676WycvJbrO4Jj3D0gw',
    appId: '1:598185368071:web:92e7dc8c33ca61af4b68a2',
    messagingSenderId: '598185368071',
    projectId: 'test-97871',
    authDomain: 'test-97871.firebaseapp.com',
    storageBucket: 'test-97871.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATKw71HWD9cUkvFLvHIe-kKtcoogYjtf0',
    appId: '1:598185368071:android:ac133e62d0ade9654b68a2',
    messagingSenderId: '598185368071',
    projectId: 'test-97871',
    storageBucket: 'test-97871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOv1tXMS0qVb9XDAyGG6Yp7E5P2vlRxLg',
    appId: '1:598185368071:ios:be97a9d9ec12309a4b68a2',
    messagingSenderId: '598185368071',
    projectId: 'test-97871',
    storageBucket: 'test-97871.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOv1tXMS0qVb9XDAyGG6Yp7E5P2vlRxLg',
    appId: '1:598185368071:ios:be97a9d9ec12309a4b68a2',
    messagingSenderId: '598185368071',
    projectId: 'test-97871',
    storageBucket: 'test-97871.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoU6Zj8bexW-wS676WycvJbrO4Jj3D0gw',
    appId: '1:598185368071:web:fad4eb10c6020dd24b68a2',
    messagingSenderId: '598185368071',
    projectId: 'test-97871',
    authDomain: 'test-97871.firebaseapp.com',
    storageBucket: 'test-97871.firebasestorage.app',
  );

}