// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-h9jNtkFrXqzjNH2ZMuLxb6ED4Vf9yr4',
    appId: '1:843399991210:web:116ef1b8de03908cfc65d3',
    messagingSenderId: '843399991210',
    projectId: 'daftarbelanja-c8ee2',
    authDomain: 'daftarbelanja-c8ee2.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-c8ee2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-c8ee2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvExq8Az-5IfY3CjHy4QUg5U7GUNVGZ1k',
    appId: '1:843399991210:android:fdf0cac8ec392d14fc65d3',
    messagingSenderId: '843399991210',
    projectId: 'daftarbelanja-c8ee2',
    databaseURL: 'https://daftarbelanja-c8ee2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-c8ee2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfQyo2JmSMXLRDOaDxTMUFYtvzhkhy0QQ',
    appId: '1:843399991210:ios:306af1a62a2b6283fc65d3',
    messagingSenderId: '843399991210',
    projectId: 'daftarbelanja-c8ee2',
    databaseURL: 'https://daftarbelanja-c8ee2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-c8ee2.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfQyo2JmSMXLRDOaDxTMUFYtvzhkhy0QQ',
    appId: '1:843399991210:ios:306af1a62a2b6283fc65d3',
    messagingSenderId: '843399991210',
    projectId: 'daftarbelanja-c8ee2',
    databaseURL: 'https://daftarbelanja-c8ee2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-c8ee2.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-h9jNtkFrXqzjNH2ZMuLxb6ED4Vf9yr4',
    appId: '1:843399991210:web:31015fbfcdc77ef1fc65d3',
    messagingSenderId: '843399991210',
    projectId: 'daftarbelanja-c8ee2',
    authDomain: 'daftarbelanja-c8ee2.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-c8ee2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-c8ee2.firebasestorage.app',
  );
}
