// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNBUWir9cZNBbyVQxFF_I_aacZCL7hTUA',
    appId: '1:324637978269:web:327a99c6b9d6fadfdd6e74',
    messagingSenderId: '324637978269',
    projectId: 'cloud-message-94269',
    authDomain: 'cloud-message-94269.firebaseapp.com',
    storageBucket: 'cloud-message-94269.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTybvIZ7LET6XdDAWKWGxkgxN0TlZZSeM',
    appId: '1:324637978269:android:86eeb110c6d266e1dd6e74',
    messagingSenderId: '324637978269',
    projectId: 'cloud-message-94269',
    storageBucket: 'cloud-message-94269.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARRy2d2SBbeBJzVi93ccppOE1IuG0NHkQ',
    appId: '1:324637978269:ios:5c9825c18ec91bf9dd6e74',
    messagingSenderId: '324637978269',
    projectId: 'cloud-message-94269',
    storageBucket: 'cloud-message-94269.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARRy2d2SBbeBJzVi93ccppOE1IuG0NHkQ',
    appId: '1:324637978269:ios:5c9825c18ec91bf9dd6e74',
    messagingSenderId: '324637978269',
    projectId: 'cloud-message-94269',
    storageBucket: 'cloud-message-94269.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNBUWir9cZNBbyVQxFF_I_aacZCL7hTUA',
    appId: '1:324637978269:web:8dbc1440533db991dd6e74',
    messagingSenderId: '324637978269',
    projectId: 'cloud-message-94269',
    authDomain: 'cloud-message-94269.firebaseapp.com',
    storageBucket: 'cloud-message-94269.firebasestorage.app',
  );

}