// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBImCWZatUALTS-PT9PWTnQaKQHQAe7Dzs',
    appId: '1:115905881020:web:b12befb97fe144fb0a81b9',
    messagingSenderId: '115905881020',
    projectId: 'mdpgold-548e8',
    authDomain: 'mdpgold-548e8.firebaseapp.com',
    databaseURL: 'https://mdpgold-548e8-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-548e8.firebasestorage.app',
    measurementId: 'G-8ZDPD3Y2KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJvXQrMDOyp3GqdxqUMStmFbVowZMmHtM',
    appId: '1:115905881020:android:5f1624ca677775620a81b9',
    messagingSenderId: '115905881020',
    projectId: 'mdpgold-548e8',
    databaseURL: 'https://mdpgold-548e8-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-548e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGOFDJUawgJOqZFywvd8ndhNcqC6OB574',
    appId: '1:115905881020:ios:2571d87ad3f165f70a81b9',
    messagingSenderId: '115905881020',
    projectId: 'mdpgold-548e8',
    databaseURL: 'https://mdpgold-548e8-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-548e8.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGOFDJUawgJOqZFywvd8ndhNcqC6OB574',
    appId: '1:115905881020:ios:2571d87ad3f165f70a81b9',
    messagingSenderId: '115905881020',
    projectId: 'mdpgold-548e8',
    databaseURL: 'https://mdpgold-548e8-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-548e8.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBImCWZatUALTS-PT9PWTnQaKQHQAe7Dzs',
    appId: '1:115905881020:web:4a127e6fbd508f290a81b9',
    messagingSenderId: '115905881020',
    projectId: 'mdpgold-548e8',
    authDomain: 'mdpgold-548e8.firebaseapp.com',
    databaseURL: 'https://mdpgold-548e8-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-548e8.firebasestorage.app',
    measurementId: 'G-TL520VFQ39',
  );
}
